apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ycs
bases:
  - ../../base
patchesStrategicMerge:
  - secrets-pipeline.yml
  - config-map.yaml
vars:
  - name: CASSANDRA_NAMESPACE_PREFIX
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: providers-kustomize
    fieldref:
      fieldpath: data.cassandra_namespace_prefix
