apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-lb-auth-encryptionkey: ""
        vault.hashicorp.com/agent-inject-template-lb-auth-encryptionkey: |
          {{- with secret "transit/git/decrypt/team12-ycs-providers" "ciphertext=vault:v1:kRpCNUzNq4wC59fSN1o/UvHfcdN9T/qjmqlp9B2OK9i5P8yDSPP5uBgigAPwqprWggvpE4NMyXruAMtN" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-lb-encryption-key: ""
        vault.hashicorp.com/agent-inject-template-lb-encryption-key: |
          {{- with secret "transit/git/decrypt/team12-ycs-providers" "ciphertext=vault:v1:7+cXwVcN3uAFVisD19jffNjTlkDrjZkV6mYH5bInifRfhBiaKqOHGhKw7H3E1dXnzsDEvP8lfCHAjVK4" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
