apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-lb-auth-encryptionkey: ""
        vault.hashicorp.com/agent-inject-template-lb-auth-encryptionkey: |
          {{- with secret "transit/git/decrypt/team4-ycs-providers" "ciphertext=vault:v1:KGT8uisnaVRTKaVoYTu42qofFXoUH+jnOFxhQoZHLq3UPO6usHTmUesgXhclfE1pD8wkaJtPcFVZUHvq" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-lb-encryption-key: ""
        vault.hashicorp.com/agent-inject-template-lb-encryption-key: |
          {{- with secret "transit/git/decrypt/team4-ycs-providers" "ciphertext=vault:v1:cwM6twYl7nKb6F8KxIDatGsNICBERYEBjOZWtrIJQJRyg9nEyew/ECC0/za5Zd3BjYzLo/cCHSkrICUh" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
