apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-lb-auth-encryptionkey: ""
        vault.hashicorp.com/agent-inject-template-lb-auth-encryptionkey: |
          {{- with secret "transit/git/decrypt/yfb-acc-ycs-providers" "ciphertext=vault:v1:OnolaLmnWXj1CYZfLsPOd/XF9gHLk4019XQ33fbbfpFzl7cD1KKj5lBR2a2N6y1jdsd/t+zdQwWcRmF+" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-lb-encryption-key: ""
        vault.hashicorp.com/agent-inject-template-lb-encryption-key: |
          {{- with secret "transit/git/decrypt/yfb-acc-ycs-providers" "ciphertext=vault:v1:o5X7vd5ZLllQVEi8JSxsfTDKsFP7jxHD3vRLwULsx9LNHVQsoWhhUAS3gd1ZbWvxyJp4rIVABysp/hLw" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
