apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: providers-pod-disruption-budget
  labels:
    name: providers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: providers
