apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  name: providers
configurations:
  - var-ref.yaml
resources:
  - cassandra-job.yaml
  - deployment.yaml
  - service-account.yaml
  - service.yaml
vars:
  - name: NAMESPACE
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: providers
    fieldref:
      fieldpath: metadata.namespace
