apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-lb-auth-encryptionkey: ""
        vault.hashicorp.com/agent-inject-template-lb-auth-encryptionkey: |
          {{- with secret "transit/git/decrypt/team5-ycs-providers" "ciphertext=vault:v1:xHdYH7SPYZCICLgTDxbwppKq/UMzhIb8oc5ivXAK4giQNogOnPyr4afh15W5462OtfUEh8g0s9NFDLIM" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-lb-encryption-key: ""
        vault.hashicorp.com/agent-inject-template-lb-encryption-key: |
          {{- with secret "transit/git/decrypt/team5-ycs-providers" "ciphertext=vault:v1:tKmGuIDHhbaqIp5vwa5IXZgZ9cwt4+UF5vbZ/eLqXpw/2Zc+6d3o84U8iMQcrAMtMHHBBXyNDJwhb3ko" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
