apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-lb-auth-encryptionkey: ""
        vault.hashicorp.com/agent-inject-template-lb-auth-encryptionkey: |
          {{- with secret "transit/git/decrypt/team9-ycs-providers" "ciphertext=vault:v1:qsBelsmMaBct+HBcF+snuNPgMF4JXJ2iiqPqMHVkRJFVTHMSk6QWaO/SHAriNovC4IkToaSKHlYVQmn0" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-lb-encryption-key: ""
        vault.hashicorp.com/agent-inject-template-lb-encryption-key: |
          {{- with secret "transit/git/decrypt/team9-ycs-providers" "ciphertext=vault:v1:9YEErnSQtOYYqCLOI7i9VLHD/ag/XCZY6JBso6Bl8oYewhYASKsMB0gjd3iGbO6tnyUxgIsi5ogPbu0G" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: KEY_256
          {{ .Data.plaintext }}
          {{- end -}}
